In [1]:
import pandas as pd
#Loading Dataset
data = pd.read_csv("kurtiData.csv")

In [2]:
#Appending producct url to a list
col=[]
for i, row in data.iterrows():
  col.append(row[2])

In [3]:
data['product_url']

0         https://www.meesho.com/alisha-refined-kurtis/p...
1         https://www.meesho.com/alisha-refined-kurtis/p...
2         https://www.meesho.com/alisha-refined-kurtis/p...
3         https://www.meesho.com/alisha-refined-kurtis/p...
4         https://www.meesho.com/alisha-refined-kurtis/p...
                                ...
425993    https://www.meesho.com/abhisarika-graceful-kur...
425994    https://www.meesho.com/abhisarika-graceful-kur...
425995    https://www.meesho.com/abhisarika-graceful-kur...
425996    https://www.meesho.com/abhisarika-graceful-kur...
425997    https://www.meesho.com/abhisarika-graceful-kur...
Name: product_url, Length: 425998, dtype: object

In [4]:
#Fetching product name from product url
import re
prodnames=[]
pattern = r"/([^/]+)/p/"
for i in range(len(col)):
  match = re.search(pattern, col[i])
  if match:
    extracted_string =match.group(1)
    prodnames.append(extracted_string)

In [5]:
# adding prodnames as an extra column to the data
data['product_name']=prodnames
data.head()

,user_id,product_id,product_url,image_url,price,rating,timestamp,product_name
0,0b32cb93b4d1467a895fdd0c0fdcac7d,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1816526580,alisha-refined-kurtis
1,a546c81dcb9346619c00f3632bb39318,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1431790209,alisha-refined-kurtis
2,6f7480ff712d42eb9be53f37641a3bf9,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1455698017,alisha-refined-kurtis
3,cf05abc75bd74b159bc91a76ad4bfbb5,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1419335880,alisha-refined-kurtis
4,893a87b0ef41435cbd40f5065bdff448,1xiamj,https://www.meesho.com/alisha-refined-kurtis/p...,https://images.meesho.com/images/products/1167...,₹293,5,1195975318,alisha-refined-kurtis

In [7]:
productRatings = data.pivot_table(index=['user_id'],columns=['product_name'],values='rating')
productRatings.head()

product_name,aagam-alluring-kurtis,aagam-attractive-kurtis,aagam-drishya-kurtis,aagam-ensemble-kurtis,aagam-fabulous-kurtis,aagam-fashionable-kurtis,aagam-graceful-kurtis,aagam-pretty-kurtis,aagam-refined-kurtis,aagam-sensational-kurtis,...,women-georgette-aline-chikankari-orange-kurti,women-georgette-straight-chikankari-yellow-kurti,women-khadi-cotton-aline-chikankari-orange-kurti,women-poly-georgette-aline-chikankari-orange-kurti,women-rayon-aline-chikankari-yellow-kurti,womens-chikankari-chiffon-kurtis,womens-embroidered-georgette-kurtis,womens-lucknowi-chikankari-chiffon-kurtis-with-inner,womens-rayon-chikankari-short-kurti-kurtis,zola-georgette-ethinic-wear-lucknowi-chikankari-kurta-for-women
user_id,,,,,,,,,,,,,,,,,,,,,
000309eea4da451792c02dcf044c6da9,NaN,NaN,NaN,NaN,NaN,3.5,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00039769c82740bb8681b29311456292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
000ab7843cc04021b2f660fb9f5a4f0c,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
000b43224557420d8eb107c93c74dd29,NaN,NaN,4.0,NaN,5.0,5.0,2.0,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
000c5704edd84f77bedf68a95c54edeb,NaN,NaN,1.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
kurtisRatings = productRatings['aagam-drishya-kurtis']
kurtisRatings.head()

user_id
000309eea4da451792c02dcf044c6da9    NaN
00039769c82740bb8681b29311456292    NaN
000ab7843cc04021b2f660fb9f5a4f0c    NaN
000b43224557420d8eb107c93c74dd29    4.0
000c5704edd84f77bedf68a95c54edeb    1.0
Name: aagam-drishya-kurtis, dtype: float64

In [10]:
similarKurtis = productRatings.corrwith(kurtisRatings)
similarKurtis = similarKurtis.dropna()
df = pd.DataFrame(similarKurtis)
df.head(10)

C:\Users\EEE\anaconda3\envs\pytorchenv\lib\site-packages\numpy\lib\function_base.py:2683: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\Users\EEE\anaconda3\envs\pytorchenv\lib\site-packages\numpy\lib\function_base.py:2542: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)

                                 0
product_name
aagam-alluring-kurtis     0.163916
aagam-attractive-kurtis   0.233029
aagam-drishya-kurtis      1.000000
aagam-ensemble-kurtis    -0.061849
aagam-fabulous-kurtis    -0.030114
aagam-fashionable-kurtis -0.045994
aagam-graceful-kurtis     0.008513
aagam-pretty-kurtis      -0.113032
aagam-refined-kurtis     -0.169574
aagam-sensational-kurtis  0.021600

In [11]:
similarKurtis.sort_values(ascending=False)

product_name
aagam-drishya-kurtis                                            1.000000
alisha-trendy-chiffon-georgette-womens-kurtis-vol-1             1.000000
women-cotton-yellow-kurti                                       1.000000
kurtis                                                          1.000000
charvi-sensational-kurtis                                       0.944911
                                                                  ...
banita-petite-kurtis                                           -0.449467
new-nayaka-gorgeous-georgette-womens-kurtis-vol-5              -0.472757
alisha-alluring-attractive-georgette-chikankari-kurtis-vol-1   -0.562500
aagyeyi-ensemble-kurtis                                        -1.000000
women-cotton-blend-aline-embroidered-yellow-kurti              -1.000000
Length: 228, dtype: float64

In [12]:
import numpy as np
productStats = data.groupby('product_name').agg({'rating': [np.size, np.mean]})
productStats.head()

                        rating
                          size      mean
product_name
aagam-alluring-kurtis      780  3.878205
aagam-attractive-kurtis    609  3.676519
aagam-drishya-kurtis      2845  3.803163
aagam-ensemble-kurtis      254  3.507874
aagam-fabulous-kurtis     7613  3.611191

In [14]:
popularKurtis = productStats['rating']['size'] >= 50
productStats[popularKurtis].sort_values([('rating', 'mean')], ascending=False)[:15]

                                                   rating
                                                     size      mean
product_name
adrika-voguish-kurtis                                4748  4.356361
adrika-ensemble-kurtis                                 68  4.294118
zola-georgette-ethinic-wear-lucknowi-chikankari...    385  4.293506
alisha-trendy-chiffon-georgette-womens-kurtis-v...     56  4.232143
chitrarekha-pretty-kurtis                             549  4.214936
women-cotton-aline-chikankari-mustard-kurti           342  4.198830
festive-special-banita-attractive-kurtis             5403  4.186933
festive-special-myra-superior-kurtis                 2138  4.155285
women-cotton-mustard-kurti                           3470  4.150720
aagyeyi-voguish-kurtis                                200  4.145000
kashvi-drishya-kurtis                               18707  4.141712
festive-special-charvi-superior-kurtis                583  4.130360
adrika-graceful-kurtis                               3238  4.101915
adrika-sensational-kurtis                             206  4.097087
kashvi-superior-kurtis                               9578  4.094801

In [15]:
#df = movieStats[popularMovies].join(pd.DataFrame(similarMovies, columns=['similarity']))

# Updated for newer Pandas releases that don't allow merging between different levels; we must flatten it first now.
mappedColumnsproductStats=productStats[popularKurtis]
mappedColumnsproductStats.columns=[f'{i}|{j}' if j != '' else f'{i}' for i,j in mappedColumnsproductStats.columns]
df = mappedColumnsproductStats.join(pd.DataFrame(similarKurtis, columns=['similarity']))

In [16]:
df.head()

                         rating|size  rating|mean  similarity
product_name
aagam-alluring-kurtis            780     3.878205    0.163916
aagam-attractive-kurtis          609     3.676519    0.233029
aagam-drishya-kurtis            2845     3.803163    1.000000
aagam-ensemble-kurtis            254     3.507874   -0.061849
aagam-fabulous-kurtis           7613     3.611191   -0.030114

In [17]:
df.sort_values(['similarity'], ascending=False)[:15]

,rating|size,rating|mean,similarity
product_name,,,
aagam-drishya-kurtis,2845,3.803163,1.000000
alisha-trendy-chiffon-georgette-womens-kurtis-vol-1,56,4.232143,1.000000
charvi-sensational-kurtis,52,3.576923,0.944911
comfy-women-kurtis,190,4.036842,0.877452
festive-special-aagyeyi-superior-kurtis,78,3.923077,0.762493
aakarsha-alluring-kurtis,61,3.622951,0.540062
myra-alluring-kurtis,158,3.854430,0.469629
trendy-drishya-kurtis,152,3.592105,0.439984
myra-fabulous-kurtis,233,3.811159,0.419139
jivika-fabulous-kurtis,185,3.827027,0.406809
festive-special-aagam-ensemble-kurtis,563,3.765542,0.393611
aakarsha-sensational-women-kurtis,52,3.519231,0.372104
adrika-attractive-kurtis,358,3.810056,0.351520
aakarsha-fashionable-kurtis,924,3.613636,0.286356
banita-ensemble-kurtis,260,3.823077,0.269663